// <auto-generated />
namespace AzurePlayground.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserEventTypeByte : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserEventTypeByte));
        
        string IMigrationMetadata.Id
        {
            get { return "201909221256039_UserEventType-Byte"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
